FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install git -y
RUN git config --global user.name lucas \
    && git config --global user.email wymam1@gmail.com